### PR TITLE
A few updates

### PR DESCRIPTION
**Pull request by vicb**
I'm happy to finally get to integrate this awesome lib into flyxc.app thanks to @flyingtof

Ref https://github.com/vicb/flyxc/pull/203

### CODE REVIEW

**Comment by mmomtchev** [comment]
is there any reason to do this?

**Comment by vicb** [comment]
Here are some reasons:

- The `.d.ts` changes are needed to access the output of the optimizer
- I find `??` more semantically correct  than the hacky `||` which doesn't short-circuit on 0

**Comment by mmomtchev** [comment]
Your comment was simultaneous with this one:
https://github.com/mmomtchev/node-gdal-async/issues/30

Normally, the same decision-making process applies, but since I won't have to make an announcement that someone contributed this change, I do not think it will have an effect on my situation. I will however make it very clear.

**Comment by vicb** [comment]
Hum, I'm sorry but I don't understand what you mean?
We just happened to comment at the same time and?

**Comment by mmomtchev** [comment]
Well, let me explain you a fundamental principle in criminal law called *"proof beyond any reasonable doubt"*. Many people believe that DNA is an absolute proof. It is not - in fact there is a very small chance that two people can fully share the same DNA - without even being related. The chance is very small - it is on the scale of 1 to trillions. The subject has been studied extensively: [The Evaluation of Forensic DNA Evidence](https://www.ncbi.nlm.nih.gov/books/NBK232610/) - so that in these cases, the explanation that someone just happened to have the same DNA as the real killer does not stand in court.

In your case, barring an eventual activation of the Infinite Improbability Drive, this is absolutely the case.

In fact, since the police tried threatening me about 8 months ago, ***there hasn't been a single comment on any project I own that is not related to this affair***

**Comment by vicb** [comment]
Ok, you're probably right.

I'm going to fork your project an make the fixes on my side - both the projects will share some DNA.

Meanwhile I have integrated your lib in a worker to isolate the global namespace pollution. It will be live in the planner of flyxc.app shortly.

Thanks for your work on `igc-xc-score` 🙏

**Comment by vicb** [comment]
Thanks @mmomtchev.

@flyingtod recently added track optimizations to flyxc, it's working very well!

**Pull request merged**
